---
- name: Copy files from one server to another
  hosts: 34.204.200.31
  become: yes

  vars:
    source_server: "54.234.29.82"
    source_path: "/var/lib/jenkins/workspace/kittu"
    destination_path: "/home/kittu"

  tasks:
  - name: Copy files from source server
    synchronize:
      mode: push
      src: "{{ /var/lib/jenkins/workspace/kittu }}"
      dest: "{{ /home/kittu }}"
      rsync_path: "rsync"
      delete: yes
    delegate_to: "{{ 54.234.29.82 }}"

