---
- name: Copy directory from server to node machine
  hosts: all
  become: yes
  tasks:
    - name: Copy directory to remote machine
      synchronize:
        src: /var/lib/jenkins/workspace/docker
        dest: /home/king
        recursive: yes
        
    - name: Build Docker image
      command: docker build -t first /home/king/docker


